version: "3.9"

services:
  go-server:
    build: .
    container_name: stock-analyzer-server
    hostname: stock-analyzer-server
    env_file:
      - .env
    networks:
      - mynet
    ports:
      - 3000:3000
    depends_on:
      postgresdb:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./:/app
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro # for aws credentials

  postgresdb:
    image: postgres:latest
    container_name: postgres_db
    expose:
      - 5432
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - mynet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
    driver: local

networks:
  mynet:
    driver: bridge
