version: "3.9"

services:
  go-server:
    build:
      context: ./server
    container_name: stock-analyzer-server
    hostname: stock-analyzer-server
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      postgresdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

    volumes:
      - ./server:/app
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro # for aws credentials

  postgresdb:
    image: postgres:latest
    container_name: postgres_db
    hostname: postgres_db
    expose:
      - 5432
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: "redis"
    hostname: redis
    image: redis:alpine
    env_file:
      - .env
    # Specify the redis.conf file to use and add a password.
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/data/:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  pg_data:
    driver: local
